import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Rootheader from "@/components/layout/rootHeader";
import RootFooter from "@/components/layout/rootFooter";
import LayoutProvider from "./layoutProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProvider>
          <Rootheader />
          <div
            style={{ minHeight: "calc(100vh)" }}
            className={` pt-[95px] bg-[#FCFCFC] pb-[50px]`}
          >
            {children}
          </div>
          <RootFooter />
        </LayoutProvider>
      </body>
    </html>
  );
}
